### PR TITLE
build: support curl >= 7.62

### PR DESCRIPTION
**Pull request by jengelh**
libs3 fails to build with 7.62 currently:

    src/request.c: In function 'request_curl_code_to_status':
    src/request.c:1703:5: error: duplicate case value
         case CURLE_SSL_CACERT:
    src/request.c:1699:5: note: previously used here
         case CURLE_PEER_FAILED_VERIFICATION:

Caught by openSUSE.

### CODE REVIEW

**Comment by bji** [comment]
Thank you.
